FROM nvidia/cuda:12.1.0-base-ubuntu20.04

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Set the working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && \
    apt-get install -y \
        python3-pip \
        git \
        python3-dev \
        ffmpeg \
        libsm6 \
        libxext6  \
        -y



# Upgrade pip
RUN python3 -m pip install --upgrade pip

# Upgrade wheel
RUN python3 -m pip install --upgrade wheel

# Ensure Installation of PyTorch, torchvision, torchaudio
RUN pip3 install torch torchvision torchaudio 

# Install any python packages you need
COPY requirements.txt requirements.txt

# install requirements
RUN python3 -m pip install -r requirements.txt
COPY . .
